// <auto-generated />
using System;
using BreadCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BreadCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220916111146_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BreadCore.Models.Brood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BroodTypeID")
                        .HasColumnType("int");

                    b.Property<int>("GebakkenFiliaalFiliaalId")
                        .HasColumnType("int");

                    b.Property<int>("HoeveelheidDerving")
                        .HasColumnType("int");

                    b.Property<int>("HoeveelheidGebakken")
                        .HasColumnType("int");

                    b.Property<DateTime>("TijdGebakken")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BroodTypeID");

                    b.HasIndex("GebakkenFiliaalFiliaalId");

                    b.ToTable("Brood");
                });

            modelBuilder.Entity("BreadCore.Models.BroodType", b =>
                {
                    b.Property<int>("BroodTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BroodTypeID"), 1L, 1);

                    b.Property<int>("BakProgramma")
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BroodTypeID");

                    b.ToTable("BroodType");
                });

            modelBuilder.Entity("BreadCore.Models.Filiaal", b =>
                {
                    b.Property<int>("FiliaalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FiliaalId"), 1L, 1);

                    b.Property<string>("FiliaalNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FiliaalId");

                    b.ToTable("Filiaal");
                });

            modelBuilder.Entity("BreadCore.Models.Medewerker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BedienerNr")
                        .HasColumnType("int");

                    b.Property<int>("FiliaalId")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wachtwoord")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FiliaalId");

                    b.ToTable("Medewerker");
                });

            modelBuilder.Entity("BreadCore.Models.Brood", b =>
                {
                    b.HasOne("BreadCore.Models.BroodType", "BroodType")
                        .WithMany()
                        .HasForeignKey("BroodTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BreadCore.Models.Filiaal", "GebakkenFiliaal")
                        .WithMany()
                        .HasForeignKey("GebakkenFiliaalFiliaalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BroodType");

                    b.Navigation("GebakkenFiliaal");
                });

            modelBuilder.Entity("BreadCore.Models.Medewerker", b =>
                {
                    b.HasOne("BreadCore.Models.Filiaal", "Filiaal")
                        .WithMany("Medewerkers")
                        .HasForeignKey("FiliaalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filiaal");
                });

            modelBuilder.Entity("BreadCore.Models.Filiaal", b =>
                {
                    b.Navigation("Medewerkers");
                });
#pragma warning restore 612, 618
        }
    }
}
